### ISSUE TITLE
how to match functions in program and their embedding in a big 3-d tensor ?   如何将程序中的函数和张量进行匹配以得到每个函数的向量表示？ 

### ISSUE THREAD

**Issue by xjy-xing** [ycachy/Codee#9]
hi, thanks for your work and source code :
    there is one question:
    After running "embedding.m", I got an amazing tensor ( kcompress * program_num * functions_num ), meanwhile, I have many programs and many functions, but **I don't know how to match the functions and their embeddings?**  how can I get the index of the function in tensor? 
    sorry for my bad English.
    当我运行全部程序后，得到一个维度为( kcompress * program_num * functions_num )的巨大张量，但在张量读取和压缩过程中，没有程序名称函数名称等信息，如果我**想要获取指定函数及其对应的嵌入向量**，我该如何操作呢？ 
    疫情形势严峻，祝您健康，平安。期待您的回复！

**Comment by whilly12** [comment]
Hi, xjy-xing. 

This is different form your question, but I have something I want to ask you.
I was also running ycachy's source codes based on the paper.

 I got the result file in the embedded directory by running RNN.py of the function embedding.

However, the next step; Tensor embedding tells me to run the embedding.m.
I'm not sure how to do it. How did xjy-xing run the embedding.m file?

1. I wonder if this requires installing an running the MATLAB library in python, or installing and running MATLAB.

2.  Looking at the content of the embedding.m in the source codes, it seems that the IDA_path is added. Is it right to put the result of function embedding in the embedded folder into IDA_path as input?  


Can you give me a step-by-step guides to make embedding.m's running
